version: "3"
services:
  bc_client:
    build:
      context: ./blockchain_client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=client
      - FLASK_ENV=development
    volumes:
      - ./blockchain_client:/app

  bc_server:
    build:
      context: ./blockchain_server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=server
      - FLASK_ENV=development
    volumes:
      - ./blockchain_server:/app



